### ISSUE TITLE
ヘッダー レスポンシブ修正

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Contact-page#3]

**Comment by nss-tomioka** [comment]
レスポンシブ時のヘッダーのデザイン、動きを修正しました。
また、スマートフォン時のヘッダーメニューを調整しています。

**Comment by nss-shimizu** [comment]
すみません、一番幅が小さい時、僕が謎にロゴを小さくする指定を入れてるので、取ってもらってもいいですか？

**Comment by nss-tomioka** [comment]
↑修正しています。
